# Generated by Django 5.0.2 on 2024-03-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='piblished_date',
            new_name='published_date',
        ),
    ]
